# Launch instances from a control node, runs some tasks on the new instances,
# Install docker, docker-compose, concourse docker image 

- name: configure concourse server
  hosts: cci 
  gather_facts: no

  vars:
    machine_type: n1-standard-1 # default
    image: ubuntu-1604-xenial-v20160930
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"
    credentials_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    user_home: "{{ lookup('env', 'USER_HOME') }}"

  tasks:

    - name: Install docker 
      apt: pkg=docker state=latest
      sudo: True

    - name: Install docker-compose 
      apt: pkg=docker-compose state=latest
      sudo: True

    - name: Install postgres
      apt: pkg=postgresql state=latest
      sudo: True

    - name: start docker service
      shell: sudo systemctl start docker

    - name: install concourse/concourse docker image from docker hub
      shell: docker pull concourse/concourse 
      sudo: True

    - name: allow port 8080
      local_action: gce_net
      args:
        name: default
        fwname: allow-http
        allowed: tcp:80,8080
        ipv4_range: 0.0.0.0/24
        service_account_email: "{{service_account_email}}"
        credentials_file: "{{credentials_file}}"
        project_id: "{{project_id}}"

 
    - name: copy key files
      copy:
        src=credentials.yml
        dest=./
 
#    - name: pull code from git 
#      git: 
#        repo=https://github.com/cisco-cis/staas-playground.git 
#        dest=./ 
#        key_file=./credentials.yml
#        accept_hostkey=yes 
#        force=yes

    - name: generate docker-compose.yaml
      shell: source -y ./staas-playground/concourse-docker/dci.sh; rm -rf docker-compose.yaml; envsubst < "template.yaml" > "docker-compose.yaml"

    - name: start concourse docker
      shell: docker-compose up -d
      sudo: True

    - name: install fly
      get_url: 
        url: http://104.198.235.44:8080/api/v1/cli?arch=amd64&platform=linux
        dest: /usr/local/bin
        mode: 0766

    - name: run hello-git pipeline
#      shell: fly -t concourse login -c http://192.168.100.4:8080
      shell: fly -t concourse set-pipeline --pipeline hello-git --config ./staas-playground/concourse-docker/hello-git.yaml --load-vars-from ./staas-playground/ci/credentials.yml

  roles:
     #- start-docker [tbd]
     #- start-concourse [tbd]
