# Launch instances from a control node, runs some tasks on the new instances,
# Install docker, docker-compose, concourse docker image 

- name: configure concourse server
  hosts: cci 
  gather_facts: no

  vars:
    machine_type: n1-standard-1 # default
    image: ubuntu-1604-xenial-v20160930
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"
    credentials_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    user_home: "{{ lookup('env', 'USER_HOME') }}"

  tasks:

    - name: Install docker 
      apt: pkg=docker state=latest
      sudo: True

    - name: Install docker-compose 
      apt: pkg=docker-compose state=latest
      sudo: True

    - name: Install postgres
      apt: pkg=postgresql state=latest
      sudo: True

    - name: start docker service
      shell: sudo systemctl start docker

    - name: install concourse/concourse docker image from docker hub
      shell: docker pull concourse/concourse 
      sudo: True

    - copy: src=./dci.sh dest={{user_home}}/dci.sh
    - copy: src=./template.yaml dest={{user_home}}/template.yaml

    - name: allow port 8080
      local_action: gce_net
      args:
        name: default
        fwname: allow-http
        allowed: tcp:80,8080
        ipv4_range: 0.0.0.0/24
        service_account_email: "{{service_account_email}}"
        credentials_file: "{{credentials_file}}"
        project_id: "{{project_id}}"

    - name:  run dci to setup keys and start concourse
      shell: cd /home/yumima; ./dci.sh
    
    - name: generate docker-compose.yaml
      shell: source -y dci.sh; rm -rf docker-compose.yaml; envsubst < "template.yaml" > "docker-compose.yaml"

    - name: start concourse docker
      shell: docker-compose up -d
      sudo: True
      
  roles:
     #- start-docker [tbd]
     #- start-concourse [tbd]
