resources:
- name: staas-ci
  type: git
  source:
    uri: git@github.com:cisco-cis/staas-playground.git
    branch: master
    private_key: {{staas-github-key}}

jobs:

- name: test-ansible-job
  plan:
  - get: staas-ci
  - task: run-ansible-command
    file: staas-ci/ci/run-ansible-example/run-ansible-task.yml
